name: Push Changes to Another Repository

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

jobs:
  push-to-other-repo:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add target repository
        run: |
          git remote add target https://ozrabal:${{ secrets.WORKFLOW_DEPLOY_TOKEN }}@github.com/ozrabal/workflow-deployment.git
          git fetch target

      - name: Push to target repository
        run: |
          git push target main

      - name: Confirm changes pushed
        run: echo "Changes pushed to target repository main branch successfully"
