name: Push Changes to Another Repository

on:
  pull_request:
    types:
      - closed

jobs:
  push-to-other-repo:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository
      - name: Checkout current repository
        uses: actions/checkout@v3

      # Step 2: Configure Git user
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 3: Add the target repository as a remote
      - name: Add target repository
        run: |
          git remote add target https://${{ secrets.WORKFLOW_DEPLOY_TOKEN }}@github.com/ozrabal/workflow-deployment.git
          git fetch target

      # Step 4: Push changes to the target repository
      - name: Push to target repository
        run: |
          git push target main

      # Optional Step 5: Log success
      - name: Confirm changes pushed
        run: echo "Changes pushed to target repository main branch successfully"
